src/main/java/com/bot/models/Cart.java
package com.bot.models;

import com.bot.db.Constants;
import com.bot.db.ProductDB;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This model class stores the Cart
 */
public class Cart implements Serializable, Constants {

    // Elements in Cart
    private ArrayList<OrderItem> itemList;

    // zero argument constructor
    public Cart() {
        itemList = new ArrayList<OrderItem>();
    }

    public ArrayList<OrderItem> getItemList() {
        return itemList;
    }

    public void setItemList(ArrayList<OrderItem> itemList) {
        this.itemList = itemList;
    }

    /**
     * Add itemToAdd to current cart. If item exists, its quantity will
     * be increased by 1
     * @param itemToAdd 
     */
    public void addItem(OrderItem itemToAdd) {
        for (OrderItem item : itemList) {
            if (item.getProduct().getProductCode().equals(itemToAdd.getProduct().getProductCode())) {
                item.setQuantity(item.getQuantity() + 1);
                return;
            }
        }
        itemList.add(itemToAdd);
    }
    
    /**
     * Overloaded for ProductCode
     * If item exists, its quantity will be increased by 1
     * Otherwise item will be added with default quantity 1
     * @param productCode 
     */
    public void addItem(String productCode) {
        for (OrderItem item : itemList) {
            if (item.getProduct().getProductCode().equals(productCode)) {
                item.setQuantity(item.getQuantity() + 1);
                return;
            }
        }
        ProductDB pdb = new ProductDB();
        Product productToAdd = pdb.getProductByProductCode(productCode);
        OrderItem itemToAdd = new OrderItem(productToAdd, 1);
        itemList.add(itemToAdd);
    }
    
    
    /**
     * Update item in cart with the quantity mentioned.
     * @param productCode
     * @param quantity 
     */
    public void updateItem(String productCode, int quantity) {
        for (OrderItem item : itemList) {
            if (item.getProduct().getProductCode().equals(productCode)) {
                if(quantity == 0){      // If quantity is zero while updating
                    removeItem(item);   // then remove the item from cart.
                    break;
                } else if (quantity == UNSPECIFIED_QUANTITY) {
                    addItem(productCode);   // read the description of addItem
                } else if (quantity == INVALID_QUANTITY) {
                    // In case of Invalid quantity don't do anything, just ignore
                } else {
                    item.setQuantity(quantity); // In case if the quantity is an perfect integer
                    break;                      // the overwrite previous quantity with new.
                }
            }
        }
    }

    /**
     * Remove itemToRemove from current cart
     * @param itemToRemove 
     */
    public void removeItem(OrderItem itemToRemove) {
        for (OrderItem item : itemList) {
            if (item.getProduct().getProductCode().equals(itemToRemove.getProduct().getProductCode())) {
                itemList.remove(item);
                return;
            }
        }
    }
    
    /**
     * This method will check if passed product in cart or not.
     * @param productCode
     * @return 
     */
    public boolean isProductInCart(String productCode) {
        for (OrderItem item : itemList) {
            if(item.getProduct().getProductCode().equals(productCode)) {
                return true;
            }
        }
        return false;
    }
    
    /**
     * This method is same is getItem, only change is in the name of the method
     *
     * @return
     */
    public ArrayList<OrderItem> getItem() {
        return itemList;
    }
    
    /**
     * Clears entire cart's content
     */
    public void emptyCart() {
        itemList.removeAll(itemList);
    }
    
    public int getCount() {
        return itemList.size();
    }
    
    public double getTotalPrice() {
        double totalPrice = 0;
        for (OrderItem item : itemList) {
            totalPrice += item.getQuantity() * item.getProduct().getPrice();
        }
        
        return totalPrice;
    }
    
}

src/main/java/com/bot/models/Order.java
package com.bot.models;

import java.io.Serializable;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collection;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * This model class will store the details of the orders.
 */

@Entity
@Table (name = "OrderDesc")
public class Order implements Serializable{
    
    @Id
    @GeneratedValue (strategy = GenerationType.AUTO)
    private int orderNumber;
    private Date date;
    @Transient
    private User user;
    private int userId;
    
    @OneToMany (cascade = CascadeType.ALL)
    private Collection<OrderItem> itemList = new ArrayList<OrderItem>(); 
    private float taxRates;
    private double totalCost;
    @Column (name = "paid")
    private boolean isPaid;
    
//zero argument constructor
    
    public Order() {
        Calendar cal = Calendar.getInstance();
        date = new Date(cal.getTimeInMillis());
        itemList = new ArrayList<OrderItem>();
        taxRates = 10.0f;
        totalCost = 0.0d;
        isPaid = false;
    }
            
  // constructor to initialize order details.
    
    public Order(Date date, int userId, ArrayList<OrderItem> itemList, 
            float taxRates, double totalCost, boolean isPaid)  {
        
        this.date = date;
        this.userId = userId;
        this.user = user;
        this.itemList = itemList;
        this.taxRates = taxRates;
        this.totalCost = totalCost;
        this.isPaid = isPaid;

     }
    
    public Date getDate() {
        
        return date;
    }
    
    public User getUser() {
        
        return user;
    }

    public ArrayList<OrderItem> getItemList() {
        return (ArrayList<OrderItem>) itemList;
    }

    public void setItemList(ArrayList<OrderItem> itemList) {
        this.itemList = itemList;
    }
    
    public double getTotalCost() {
        
        return totalCost;
    }

    public float getTaxRates() {
        
        return taxRates;
    }
    
    
    public boolean getPaid() {
        
        return isPaid;
    }   
    
    public void setDate(Date date) {
        this.date = date;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public void setTotalCost(double totalCost) {
        this.totalCost = totalCost;
    }
    
    public void setTaxRates(float taxRates) {
        this.taxRates = taxRates;
    }    

    public void setIsPaid(boolean isPaid) {
        this.isPaid = isPaid;
    }

    public int getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(int orderNumber) {
        this.orderNumber = orderNumber;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }
    
    
    
    public double getTotalPrice() {
        double totalPrice = 0;
        for (OrderItem item : itemList) {
            totalPrice += item.getQuantity() * item.getProduct().getPrice();
        }
        
        return totalPrice;
    }
    
    public double getTotalTax() {
        return (taxRates/100)*getTotalPrice();
    }
}

src/main/java/com/bot/servlets/AdminController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bot.servlets;

import com.bot.db.Constants;
import com.bot.db.OrderDB;
import com.bot.db.UserDB;
import com.bot.models.Order;
import com.bot.models.User;
import java.io.IOException;
import java.util.List;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 *
 * @author tarun
 */
public class AdminController extends HttpServlet implements Constants {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        String action = request.getParameter("action");
        HttpSession session = request.getSession();
        
        User user = (User) session.getAttribute(USER);
        String loginError = "";
        if(user == null || user.getIsAdmin() == 0 ) {
            loginError += "Login with Admin account";
            request.setAttribute("loginError", loginError);
            getServletContext().getRequestDispatcher("/signup.jsp").forward(request, response);
            return;
        }
        
        if(VIEW_ORDERS.equals(action)) {
            OrderDB odb = new OrderDB();
            List<Order> orders = odb.getAllOrders();
            UserDB udb = new UserDB();
            for(Order order : orders) {
                user = udb.getUserByUserID(order.getUserId());
                order.setUser(user);
            }
            
            session.setAttribute(THE_ORDERS, orders);
            getServletContext().getRequestDispatcher("/orderList.jsp").forward(request, response);
            return;
        } else {
            getServletContext().getRequestDispatcher("/admin.jsp").forward(request, response);
            return;
        }
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        doGet(req, resp);
    }
}

src/main/java/com/bot/servlets/CatalogControllerServlet.java
package com.bot.servlets;

import com.bot.db.CatalogDB;
import com.bot.db.ProductDB;
import com.bot.models.Catalog;
import com.bot.models.Product;
import java.io.IOException;
import java.util.List;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * This servlets checks and return product java beans, 
 * based on the product code or product name in the
 * request object.
 */
public class CatalogControllerServlet extends HttpServlet {

    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        //doing all the work in doPost so transfer doGet call to doPost.
        doPost(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        
        CatalogDB cdb = new CatalogDB();
        List<Catalog> catalogs = cdb.getCatalogs();
        request.setAttribute("catalogs", catalogs);
        
        ProductDB productDb = new ProductDB();
        String productCode = (String) request.getParameter("productCode");
        if(productCode != null){
            Product product = productDb.getProductByProductCode(productCode);
            if(product != null){
                request.setAttribute("product", product);
                getServletContext().getRequestDispatcher("/viewProduct.jsp").forward(request,response);
                return;
            }
        }
        
        String category = (String) request.getParameter("catalogCategory");
        if(category != null){
            List<Product> products = productDb.getProductsByCategory(category);
            request.setAttribute("products", products);
            getServletContext().getRequestDispatcher("/catalogList.jsp").forward(request,response);
            return;
        }

        List<Product> products = productDb.getProducts();
        request.setAttribute("products", products);
        getServletContext().getRequestDispatcher("/catalogList.jsp").forward(request,response);  
        return;
    }

}

src/main/java/com/bot/servlets/ImageServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bot.servlets;

import com.bot.util.Util;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import javax.imageio.ImageIO;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author tarun
 */
public class ImageServlet extends HttpServlet {
    
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        String UPLOAD_DIRECTORY = Util.getImageUploadLocation();
        response.setContentType("image/jpeg");
        String fileName = request.getParameter("imageId");
//        UPLOAD_DIRECTORY += System.getProperty("user.home");
//        if(!UPLOAD_DIRECTORY.contains("openshift")){
//            UPLOAD_DIRECTORY += "/NetBeansProjects/images";
//        }
        
        
        File image = new File(UPLOAD_DIRECTORY + File.separator + fileName);
        
        BufferedImage bi = ImageIO.read(image);
        OutputStream out = response.getOutputStream();
        ImageIO.write(bi, "jpg", out);
        out.close();
        
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        doGet(request,response);
    }
    
}

src/main/java/com/bot/servlets/LoginController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bot.servlets;

import static com.bot.db.Constants.*;
import com.bot.db.UserDB;
import com.bot.models.User;
import com.bot.util.PasswordUtil;
import java.io.IOException;
import java.io.PrintWriter;
import javax.persistence.NoResultException;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 *
 * @author tarun
 */
public class LoginController extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        String action=request.getParameter("action");
        if("logout".equals(action)) {
            HttpSession session = request.getSession();
            session.removeAttribute(USER);
            session.removeAttribute(SHOPPING_CART);
            getServletContext().getRequestDispatcher("/index.jsp").forward(request, response);
            return;
        }
        doPost(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        String email = request.getParameter("email");
        String password = request.getParameter("password");
        HttpSession session = request.getSession();
        String loginError ="";
        password = PasswordUtil.hashPassword(password);

        UserDB udb = new UserDB();
        User user = null;
        try {
            user = udb.getUserByEmail(email);
        } catch (NoResultException e) {
            loginError += "Username/Password Incorrect";
            getServletContext().getRequestDispatcher("/signup.jsp").forward(request, response);
        }
        if (user.getPassword().equals(password)) {
            session.setAttribute(USER, user);
            session.removeAttribute(SHOPPING_CART);
            if(user.getIsAdmin() == 1) {
                getServletContext().getRequestDispatcher("/admin.jsp").forward(request, response);
                return;
            }
            String fwdString = (String) session.getAttribute(FWD_STR);
            if(fwdString != null) {
                getServletContext().getRequestDispatcher(fwdString).forward(request, response);
                return;
            }
            response.sendRedirect("/biteontime/CatalogControllerServlet");
            return;
        } else {
            loginError += "Username/Password Incorrect";
            request.setAttribute("loginError", loginError);
            request.setAttribute("email", email);
            getServletContext().getRequestDispatcher("/signup.jsp").forward(request, response);
            return;
        }
    }

}

src/main/webapp/admin.jsp
<!DOCTYPE html>
<html>
    <head>
        <title>Bite on Time</title>
<!--        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
        <link rel="stylesheet" type="text/css" href="css/main.css">
        <link rel="stylesheet" type="text/css" href="css/order.css">
        <link rel="stylesheet" type="text/css" href="css/buttons.css">
    </head>
    <body>
    <div id="super">
    <%@ include file="header.jsp" %>
        <%@ include file="user-navigation.jsp" %>
        <div id="main_page">

            <%@ include file="site-navigation.jsp" %>  
            <%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
            <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
            
            <div id="description">
                <div id="breadcrumb">
                    <p><a href="index.jsp">Home</a> >> <a href="order.jsp">Order</a> </p>
                </div>
                
                <h3>Administrator Menu</h3>
                <form action="AdminController" method="POST">
                    <button type="submit" value="viewOrders" name="action" >Display All Orders</button>                
                </form>
            </div> 
        </div>
<%@ include file="footer.jsp" %>
    </div>
    </body>
</html>

src/main/webapp/catalog.jsp
<!DOCTYPE html>
<html>
<head>
    <title>Bite on Time</title>
<!--    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
    <link rel="stylesheet" type="text/css" href="css/main.css">
    <link rel="stylesheet" type="text/css" href="css/catalog.css">
    <link rel="stylesheet" type="text/css" href="css/product.css">
</head>
<body>
    <div id="super">

        <%@ include file="header.jsp" %>


        <%@ include file="user-navigation.jsp" %>
        

        <div id="main_page">

            <%@ include file="site-navigation.jsp" %>

            <div>
                <form action="CatalogControllerServlet" method="post">
                    <select name="category">
                        <option value="beverages">Beverage</option>
                        <option value="bakery">Bakery</option>                    
                    </select>
                    <input type="submit" value="Apply Filter">
                </form>
            </div>

            <div id="description">
                <ol>
                    <li>                                                 
                        <table>
                            <tr>
                                <th rowspan="2"><a href="product.jsp"><img src="images/vanilla_IC_SB.jpg" alt="vanila Ice Cream"></a></th>
                                <th colspan="2" class="pro_description"><a href="product.jsp">Starbucks Vanilla Iced Coffee</a></th>
                            </tr>
                            <tr>
                                <td>Nutrition: 100 Cal</td>
                                <td class = "price">
                                    <table>
                                        <tr>
                                            <td>$7</td>
                                            <td><a href="#"><img src="images/add-to-cart-icon.jpg" alt="add to card"></a></td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table></li>
                        <li>
                            <table>
                                <tr>
                                    <th rowspan="2"><a href="#"><img src="images/HamSwissPanini_SB.jpg" alt="Ham Swiss Panini"></a></th>
                                    <th colspan="2" class="pro_description"><a href="#">Ham and Swiss cheese with Dijon mustard on a focaccia roll.</a></th>
                                </tr>
                                <tr>
                                    <td>Nutrition: 200 Cal</td>
                                    <td class = "price">
                                        <table>
                                            <tr>
                                                <td>$15</td>
                                                <td><a href="#"><img src="images/add-to-cart-icon.jpg" alt="add to cart"></a></td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </table></li>
                            <li>
                                <table>
                                    <tr>
                                        <th rowspan="2"><a href="#"><img src="images/ChocoCakePop_SB.jpg" alt="Chocolate cake"></a></th>
                                        <th colspan="2" class="pro_description"><a href="#">Chocolate cake mixed with chocolate butter cream, dipped in dark chocolate and topped with sugar sprinkles.</a></th>
                                    </tr>
                                    <tr>
                                        <td>Nutrition: 250 Cal</td>
                                        <td class = "price">
                                            <table>
                                                <tr>
                                                    <td>$10</td>
                                                    <td><a href="#"><img src="images/add-to-cart-icon.jpg" alt="add to cart"></a></td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </table></li>
                            </ol>
                            
                        </div>
                    </div>


                    <%@ include file="footer.jsp" %>
                </div>
            </body>
            </html>

src/main/webapp/contact.jsp
<!DOCTYPE html>
<html>
<head>
    <title>Bite on Time</title>
<!--    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
    <link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
    <div id="super">
        <%@ include file="header.jsp" %>
        <%@ include file="user-navigation.jsp" %>


        <div id="main_page">

            <%@ include file="site-navigation.jsp" %>  

            <div id="description">

                <div id="breadcrumb">    
                <p><a href="index.jsp">Home</a> >> <a href="contact.jsp">Contact Us</a></p>
            </div>
                <h3><br>Have some feedback for us? </h3>

                <h4>Contact Us

                    Email us: biteontime@gmail.com<br><br>
                    Call us: 704-543-7653<br>
                </h4>
                <form>

                  <table>
                   <tr>
                    <td>Name</td>
                    <td><input type="text" size="20" name="t3"/></td>
                </tr>
                <tr>
                    <td>Email</td>
                    <td><input type="text" size="20" name="t4"/></td>
                </tr>

                <tr>
                    <td>Feedback</td>
                    <td><textarea rows="5" cols="21"></textarea></td>
                </tr>
                <tr><td></td>
                   <td> <input type="submit" value="Submit"/></td>

               </tr>

           </table>


       </form>
   </div>  
</div>


<%@ include file="footer.jsp" %>
</div>
</body>
</html>

src/main/webapp/footer.jsp
		<footer> 
            <p>&copy; Bite on Time's Inc.</p>
        </footer>

src/main/webapp/header.jsp
        <header>
            <img src="images/logo.png" alt="banner">
            <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
            <c:if test="${theUser eq null}">
            <p>
                Not Signed in, <a href="signup.jsp">Sign in</a><br><br>
                <a href="signup.jsp">Sign Up</a>
            </p>
            </c:if>
            <c:if test="${theUser ne null}">
                <p>
                    Welcome, ${theUser.firstName} <br><br>
                <a href="LoginController?action=logout" >Logout</a>
                </p>
                
            </c:if>
            
        </header>

src/main/webapp/insertCatalog.jsp
<!DOCTYPE html>
<html>
    <head>
        <title>Bite on Time</title>
<!--        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
        <link rel="stylesheet" type="text/css" href="css/main.css">
        <link rel="stylesheet" type="text/css" href="css/mycart.css">
        <link rel="stylesheet" type="text/css" href="css/buttons.css">
    </head>
    <body>
        <div id="super">
            <%@ include file="header.jsp" %>

            <%@ include file="user-navigation.jsp" %>

            <%@ include file="site-navigation.jsp" %>
            
            <div id="main_page">
                <p>${message}</p>
                <form action="DBController" method="GET" enctype="multipart/form-data">
                    <table>
                        <tr><td>Catalog Name</td><td><input type="text" name="catalogName" value="${catalogName}" /></td></tr>
                        <tr><td></td><td><button type="submit" name="action" value="addCatalogToDB" class="button">Add to DB</button></td></tr>
                    </table>
                    <a href="insertProduct.jsp" class="button">Back</a>                    
                </form>
            </div>


            <%@ include file="footer.jsp" %>
        </div>
    </body>
</html>

src/main/webapp/order.jsp
<!DOCTYPE html>
<html>
    <head>
        <title>Bite on Time</title>
<!--        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
        <link rel="stylesheet" type="text/css" href="css/main.css">
        <link rel="stylesheet" type="text/css" href="css/order.css">
        <link rel="stylesheet" type="text/css" href="css/buttons.css">
    </head>
    <body>
    <div id="super">
    <%@ include file="header.jsp" %>
        <%@ include file="user-navigation.jsp" %>
        <div id="main_page">

            <%@ include file="site-navigation.jsp" %>  
            <%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
            <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
            
            <div id="description">
                <div id="breadcrumb">
                    <p><a href="index.jsp">Home</a> >> <a href="order.jsp">Order</a> </p>
                </div>
                <h3>Invoice</h3>
        
                <fmt:formatDate type="date" value="${currentOrder.date}" />
        
                <h3>Ship/Bill To</h3>
                Mr. ${theUser.firstName}&nbsp;${theUser.lastName} <br>
                ${theUser.addressField1} <br>
                ${theUser.addressField2} <br>
                ${theUser.city} <br>
                ${theUser.state}-${theUser.postCode}<br>
                <br><br>
               
                <form action="OrderController">
                
                <table class="order_table">
                    <tr>
                        <th class="item_col">Item</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                    </tr>
                    <c:forEach var="orderItem" items="${currentOrder.itemList}">
                    <tr>
                        <td class="item_col">${orderItem.product.productName}</td>
                        <td class="align_right">${orderItem.product.price}</td>
                        <td class="align_right"><input type="text" name="quantity" value="${orderItem.quantity}" size="2" class="align_right" disabled/></td>
                        <td class="align_right">${orderItem.product.price * orderItem.quantity}</td>
                    </tr>
                    </c:forEach>
                    <tr>
                        <td class="item_col"> </td>
                        <td class="align_right"> </td>
                        <td class="align_right">Total Price</td>
                        <td class="align_right">${currentOrder.totalPrice}</td>
                    </tr>
                    <tr>
                        <td class="item_col"> </td>
                        <td class="align_right"> </td>
                        <td class="align_right">Taxes</td>
                        <td class="align_right"><fmt:formatNumber value="${currentOrder.totalTax}" currencySymbol="$" type="currency"/></td>
                    </tr>
                    <tr>
                        <td class="item_col"> </td>
                        <td class="align_right"> </td>
                        <td class="align_right">Subtotal</td>
                        <td class="align_right"><fmt:formatNumber value="${currentOrder.totalPrice + currentOrder.totalTax}" currencySymbol="$" type="currency"/></td>
                    </tr>
                </table>
                <p>
                    <a href="mycart.jsp" class="button">Back to Cart</a>
                    <button type="submit" name="action" value="purchase" class="button">Purchase</button>
                </p>
                </form>
            </div> 
        </div>
<%@ include file="footer.jsp" %>
    </div>
    </body>
</html>

src/main/webapp/user-navigation.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<nav>
    <ul>
        <li><a href="signup.jsp">Sign In</a></li>
        <li><a href="mycart.jsp">Cart
                <c:if test="${theShoppingCart.count gt 0}">
                    <span>(${theShoppingCart.count})</span>
                </c:if>
            </a>
        </li>
        <li ><a href="OrderController?action=viewOrders">My Orders</a></li>
    </ul>
</nav>